<?php

return [
    'irregular' => [
        // f/fe → ves
        'knife' => 'knives',
        'life' => 'lives',
        'wife' => 'wives',
        'leaf' => 'leaves',
        'loaf' => 'loaves',
        'wolf' => 'wolves',
        'calf' => 'calves',
        'elf' => 'elves',
        'half' => 'halves',
        'self' => 'selves',
        'shelf' => 'shelves',
        'thief' => 'thieves',

        // vowel changes
        'man' => 'men',
        'woman' => 'women',
        'tooth' => 'teeth',
        'foot' => 'feet',
        'goose' => 'geese',
        'mouse' => 'mice',
        'louse' => 'lice',
        'die' => 'dice',
        'ox' => 'oxen',

        // Latin/Greek origin
        'cactus' => 'cacti',
        'focus' => 'foci',
        'fungus' => 'fungi',
        'nucleus' => 'nuclei',
        'syllabus' => 'syllabi',
        'analysis' => 'analyses',
        'diagnosis' => 'diagnoses',
        'thesis' => 'theses',
        'crisis' => 'crises',
        'criterion' => 'criteria',
        'phenomenon' => 'phenomena',
        'datum' => 'data',
        'medium' => 'media',
        'alumnus' => 'alumni',

        // child/children type
        'child' => 'children',
        'person' => 'people',

        // common irregulars
        'aircraft' => 'aircraft',
        'sheep' => 'sheep',
        'deer' => 'deer',
        'fish' => 'fish', // though 'fishes' also exists
        'species' => 'species',
        'series' => 'series',
        'bison' => 'bison',
        'salmon' => 'salmon',
        'moose' => 'moose',
        'trout' => 'trout',
        'swine' => 'swine',
        'hovercraft' => 'hovercraft',
        'shrimp' => 'shrimp', // sometimes 'shrimps' in UK

        // Exceptions
        'index' => 'indices', // or 'indexes'
        'appendix' => 'appendices', // or 'appendixes'
        'matrix' => 'matrices',
        'vertex' => 'vertices',
    ],

    'Uncountable' => [
        'advice',
        'air',
        'alcohol',
        'anger',
        'art',
        'beauty',
        'bread',
        'butter',
        'cheese',
        'clothing',
        'coffee',
        'commerce',
        'courage',
        'damage',
        'data',
        'education',
        'equipment',
        'evidence',
        'fiction',
        'flour',
        'food',
        'fun',
        'furniture',
        'gas',
        'gold',
        'gossip',
        'grass',
        'happiness',
        'harm',
        'homework',
        'honesty',
        'imagination',
        'information',
        'intelligence',
        'iron',
        'jewelry',
        'knowledge',
        'laughter',
        'leather',
        'leisure',
        'literature',
        'love',
        'luggage',
        'mathematics',
        'meat',
        'milk',
        'money',
        'music',
        'news',
        'oil',
        'oxygen',
        'paper',
        'patience',
        'peace',
        'pollution',
        'progress',
        'rain',
        'reliability',
        'rice',
        'salt',
        'sand',
        'shopping',
        'silence',
        'sleep',
        'smoke',
        'snow',
        'software',
        'soup',
        'speed',
        'strength',
        'sugar',
        'tea',
        'thunder',
        'time',
        'traffic',
        'transportation',
        'trust',
        'violence',
        'water',
        'weather',
        'weight',
        'wisdom',
        'wood',
        'work',
    ],

];